name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
    
    - name: Run dotenv-linter with reviewdog
  # You may pin to the exact commit or the version.
  # uses: dotenv-linter/action-dotenv-linter@d776880abf5c686778651261859697508e6fc3e1
  uses: dotenv-linter/action-dotenv-linter@v2
  with:
    # GITHUB_TOKEN
    github_token: # optional, default is ${{ github.token }}
    # dotenv-linter flags. (dotenv-linter <dotenv_linter_flags>)
    dotenv_linter_flags: # optional, default is 
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is dotenv-linter
    # Reporter of reviewdog command [github-pr-check,github-pr-review,github-code-suggestions].
Default is github-pr-check.

    reporter: # optional, default is github-pr-check
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
